export const PROJECT_DATA = [
  {
    title: "NOVUFresh",
    img: "https://picsum.photos/300/150",
    tag1: "HTML",
    tag2: "JS",
    tag3: "Sass",
    gitUrl: "https://github.com/",
    liveUrl: "https://github.com/",
    uiUrl: "https://github.com/",
  },
  {
    title: "Sample Text2",
    img: "https://picsum.photos/300/150",
    tag1: "Text",
    tag2: "Text",
    tag3: "Text",
    gitUrl: "https://github.com/",
    liveUrl: "https://github.com/",
    uiUrl: "https://github.com/",
  },
  {
    title: "Sample Text3",
    img: "https://picsum.photos/300/150",
    tag1: "Text",
    tag2: "Text",
    tag3: "Text",
    gitUrl: "https://github.com/",
    liveUrl: "https://github.com/",
    uiUrl: "https://github.com/",
  },
  {
    title: "Sample Text4",
    img: "https://picsum.photos/300/150",
    tag1: "Text",
    tag2: "Text",
    tag3: "Text",
    gitUrl: "https://github.com/",
    liveUrl: "https://github.com/",
    uiUrl: "https://github.com/",
  },
];
